[package]
name = "irc-rust"
version = "0.1.0"
authors = ["mo_blaa <moblaa@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rand = "0.7.3"